import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Upload, FileText, Users, Target, Sparkles, CheckCircle2, BriefcaseBusiness, LogOut, LayoutDashboard, Search, BarChart3, ArrowLeft, Download, Clock3, UserRound, ShieldCheck } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000/api';
type User={id:number;name:string;email:string;role:'candidate'|'admin'};
type Job={id:number;title:string;description:string;required_skills:string[];created_at:string};
type Resume={id:number;job_id:number;filename:string;name:string;email?:string;phone?:string;parsed_data:any;skill_score:number;semantic_score:number;experience_score:number;education_score:number;certification_score:number;final_score:number;recommendation:string};
type AppItem={id:number;status:string;ai_suggestions:string[];applied_at:string;updated_at:string;job:Job;resume:Resume;candidate_name?:string;candidate_email?:string};

async function api(path:string, options:RequestInit={}){
  const token=localStorage.getItem('resume_token');
  const headers=new Headers(options.headers||{});
  if(token) headers.set('X-User-Token',token);
  const r=await fetch(`${API}${path}`,{...options,headers});
  const data=await r.json().catch(()=>null);
  if(!r.ok) throw new Error(data?.detail||'Request failed');
  return data;
}

function App(){
 const [user,setUser]=useState<User|null>(null);
 const [authMode,setAuthMode]=useState<'login'|'register'>('login');
 const [authRole,setAuthRole]=useState<'candidate'|'admin'>('candidate');
 const [authName,setAuthName]=useState(''); const [authEmail,setAuthEmail]=useState(''); const [authPassword,setAuthPassword]=useState(''); const [authError,setAuthError]=useState('');
 const [view,setView]=useState('dashboard');
 useEffect(()=>{const saved=localStorage.getItem('resume_user'); if(saved)setUser(JSON.parse(saved));},[]);
 if(!user) return <Auth mode={authMode} setMode={setAuthMode} role={authRole} setRole={setAuthRole} name={authName} setName={setAuthName} email={authEmail} setEmail={setAuthEmail} password={authPassword} setPassword={setAuthPassword} error={authError} onSubmit={async()=>{try{setAuthError('');const data=await api(authMode==='login'?'/auth/login':'/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(authMode==='login'?{email:authEmail,password:authPassword}:{name:authName,email:authEmail,password:authPassword,role:authRole})});localStorage.setItem('resume_token',data.token);localStorage.setItem('resume_user',JSON.stringify(data.user));setUser(data.user);}catch(e:any){setAuthError(e.message)}}}/>;
 const logout=()=>{localStorage.removeItem('resume_token');localStorage.removeItem('resume_user');setUser(null);};
 return <div className="app"><Sidebar user={user} view={view} setView={setView} logout={logout}/>{user.role==='admin'?<AdminPortal view={view} setView={setView}/>:<CandidatePortal view={view} setView={setView}/>}</div>
}

function Auth(p:any){return <div className="auth-page"><div className="auth-card"><div className="brand big"><Sparkles/><span>ResumeAI</span></div><div className="eyebrow">AI RECRUITMENT PLATFORM</div><h1>{p.mode==='login'?'Welcome back':'Create your account'}</h1><p>{p.mode==='login'?'Sign in to access your portal.':'Choose your portal and start using AI-powered resume screening.'}</p>{p.mode==='register'&&<input placeholder="Full name" value={p.name} onChange={e=>p.setName(e.target.value)}/>}<input placeholder="Email" type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)}/><input placeholder="Password (6+ characters)" type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)}/>{p.mode==='register'&&<div className="role-switch"><button className={p.role==='candidate'?'selected':''} onClick={()=>p.setRole('candidate')}><UserRound/> Candidate</button><button className={p.role==='admin'?'selected':''} onClick={()=>p.setRole('admin')}><ShieldCheck/> Admin</button></div>}{p.error&&<div className="error">{p.error}</div>}<button className="primary full" onClick={p.onSubmit}>{p.mode==='login'?'Sign in':'Create account'}</button><button className="link-btn" onClick={()=>p.setMode(p.mode==='login'?'register':'login')}>{p.mode==='login'?"Don't have an account? Register":"Already have an account? Sign in"}</button></div></div>}

function Sidebar({user,view,setView,logout}:{user:User;view:string;setView:(v:string)=>void;logout:()=>void}){const items=user.role==='admin'?[['dashboard','Dashboard',LayoutDashboard],['jobs','Jobs',BriefcaseBusiness],['applicants','Applicants',Users],['reports','Reports',BarChart3]]:[['dashboard','Find Jobs',Search],['applications','My Applications',FileText],['improvement','Resume Improvement',Sparkles]];return <aside><div className="brand"><Sparkles/><span>ResumeAI</span></div><div className="portal-label">{user.role==='admin'?'ADMIN PORTAL':'CANDIDATE PORTAL'}</div><div className="user-box"><div className="avatar">{user.name.charAt(0).toUpperCase()}</div><div><strong>{user.name}</strong><small>{user.email}</small></div></div>{items.map(([key,label,Icon]:any)=><button key={key} className={`nav ${view===key?'active':''}`} onClick={()=>setView(key)}><Icon/> {label}</button>)}<button className="nav logout" onClick={logout}><LogOut/> Sign out</button></aside>}

function AdminPortal({view,setView}:{view:string;setView:(v:string)=>void}){const [jobs,setJobs]=useState<Job[]>([]);const [apps,setApps]=useState<AppItem[]>([]);const [stats,setStats]=useState<any>({});const [selected,setSelected]=useState<AppItem|null>(null);const [title,setTitle]=useState('Machine Learning Engineer');const [description,setDescription]=useState('We are looking for a Machine Learning Engineer with 2 years experience in Python, machine learning, TensorFlow, SQL and Flask. A bachelor degree is preferred. Docker and AWS are desirable.');const [msg,setMsg]=useState('');
 const load=async()=>{try{setJobs(await api('/admin/jobs'));setApps(await api('/admin/applications'));setStats(await api('/admin/stats'));}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);
 const create=async()=>{try{const j=await api('/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description})});setJobs(x=>[j,...x]);setMsg('Job published. Candidates can now apply immediately.');}catch(e:any){setMsg(e.message)}};
 const status=async(id:number,s:string)=>{try{await api(`/admin/applications/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:s})});await load();if(selected)setSelected({...selected,status:s});}catch(e:any){setMsg(e.message)}};
 if(selected) return <main><button className="back" onClick={()=>setSelected(null)}><ArrowLeft/> Back to applicants</button><CandidateAdminDetail item={selected} updateStatus={status}/></main>;
 return <main><header><div><div className="eyebrow">ADMIN PORTAL</div><h1>{view==='dashboard'?'Recruitment Dashboard':view==='jobs'?'Job Management':view==='applicants'?'Candidate Screening':'Reports & Analytics'}</h1><p>Post jobs, receive applications and review AI-analyzed candidates automatically.</p></div></header>{msg&&<div className="message">{msg}</div>}{view==='dashboard'&&<><Stats stats={stats}/><section className="panel"><div className="section-head"><div><h2>Recent applications</h2><p>Every candidate application is automatically analyzed at upload time.</p></div><button className="secondary" onClick={()=>setView('applicants')}>View all</button></div><ApplicantTable apps={apps.slice(0,5)} onSelect={setSelected}/></section></>}{view==='jobs'&&<><section className="grid"><div className="panel"><h2>Post a new job</h2><label>Job title</label><input value={title} onChange={e=>setTitle(e.target.value)}/><label>Job description</label><textarea rows={9} value={description} onChange={e=>setDescription(e.target.value)}/><button className="primary" onClick={create}>Publish Job</button></div><section className="panel"><h2>Published jobs</h2>{jobs.map(j=><div className="job-card" key={j.id}><div><strong>{j.title}</strong><small>{j.required_skills.join(' • ')}</small></div><span>{apps.filter(a=>a.job.id===j.id).length} applicants</span></div>)}</section></section></>}{view==='applicants'&&<section className="panel"><div className="section-head"><div><h2>All candidates</h2><p>ATS score, skill match, semantic match and AI recommendations.</p></div></div><ApplicantTable apps={apps} onSelect={setSelected} admin/></section>}{view==='reports'&&<Reports apps={apps} stats={stats}/>}</main>}

function CandidatePortal({view,setView}:{view:string;setView:(v:string)=>void}){const [jobs,setJobs]=useState<Job[]>([]);const [apps,setApps]=useState<AppItem[]>([]);const [selected,setSelected]=useState<AppItem|null>(null);const [msg,setMsg]=useState('');const [loading,setLoading]=useState(false);const load=async()=>{try{setJobs(await api('/candidate/jobs'));setApps(await api('/candidate/applications'));}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);const apply=async(job:Job,file:File)=>{setLoading(true);try{const fd=new FormData();fd.append('file',file);await api(`/candidate/jobs/${job.id}/apply`,{method:'POST',body:fd});setMsg(`Application submitted for ${job.title}. Your resume was analyzed automatically.`);await load();setView('applications')}catch(e:any){setMsg(e.message)}finally{setLoading(false)}};
 if(selected)return <main><button className="back" onClick={()=>setSelected(null)}><ArrowLeft/> Back to applications</button><CandidateDetail item={selected}/></main>;
 return <main><header><div><div className="eyebrow">CANDIDATE PORTAL</div><h1>{view==='dashboard'?'Find your next opportunity':view==='applications'?'My Applications':'Resume Improvement'}</h1><p>Apply once and let AI analyze your resume against the job requirements automatically.</p></div></header>{msg&&<div className="message">{msg}</div>}{view==='dashboard'&&<section className="job-grid">{jobs.map(j=><JobCard key={j.id} job={j} onApply={apply} loading={loading}/>)}</section>}{view==='applications'&&<section className="panel"><h2>Application status</h2>{apps.length?<div className="application-list">{apps.map(a=><button className="application-card" key={a.id} onClick={()=>setSelected(a)}><div><strong>{a.job.title}</strong><small>Applied {new Date(a.applied_at).toLocaleDateString()}</small></div><div><span className={`status ${a.status.toLowerCase().replaceAll(' ','-')}`}>{a.status}</span><b>{a.resume.final_score.toFixed(1)}% ATS</b></div></button>)}</div>:<Empty text="You have not applied for any jobs yet."/>}</section>}{view==='improvement'&&<Improvement apps={apps} onSelect={setSelected}/>}</main>}

function JobCard({job,onApply,loading}:{job:Job;onApply:(j:Job,f:File)=>void;loading:boolean}){const [file,setFile]=useState<File|null>(null);return <div className="panel job-card-large"><div className="job-icon"><BriefcaseBusiness/></div><h2>{job.title}</h2><p>{job.description}</p><div>{job.required_skills.map(s=><span className="chip" key={s}>{s}</span>)}</div><label className="drop compact"><Upload size={26}/><strong>{file?file.name:'Upload your resume'}</strong><span>PDF / DOCX</span><input type="file" accept=".pdf,.docx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="primary full" disabled={!file||loading} onClick={()=>file&&onApply(job,file)}>{loading?'AI analyzing…':'Apply & Analyze Resume'}</button></div>}

function CandidateDetail({item}:{item:AppItem}){const r=item.resume;return <><section className="panel hero-detail"><div><div className="eyebrow">APPLICATION #{item.id}</div><h1>{item.job.title}</h1><span className={`status ${item.status.toLowerCase().replaceAll(' ','-')}`}>{item.status}</span></div><div className="ats-big">{r.final_score.toFixed(1)}<small>ATS MATCH</small></div></section><section className="metric-grid"><Metric label="Skill Match" value={r.skill_score}/><Metric label="Semantic Match" value={r.semantic_score}/><Metric label="Experience" value={r.experience_score}/><Metric label="Education" value={r.education_score}/><Metric label="Certifications" value={r.certification_score}/></section><section className="grid"><section className="panel"><h2>AI analysis</h2><h3>Matched skills</h3>{(r.parsed_data.matched_skills||[]).map((s:string)=><span className="chip good" key={s}>{s}</span>)}<h3 className="mt">Missing skills</h3>{(r.parsed_data.missing_skills||[]).map((s:string)=><span className="chip missing" key={s}>{s}</span>)}</section><section className="panel"><h2>AI improvement suggestions</h2>{item.ai_suggestions.map((s,i)=><div className="suggestion" key={i}><Sparkles/> <span>{s}</span></div>)}</section></section></>}
function CandidateAdminDetail({item,updateStatus}:{item:AppItem;updateStatus:(id:number,s:string)=>void}){return <><section className="panel hero-detail"><div><div className="eyebrow">AI CANDIDATE ANALYSIS</div><h1>{item.candidate_name}</h1><p>{item.candidate_email} • {item.job.title}</p><span className={`status ${item.status.toLowerCase().replaceAll(' ','-')}`}>{item.status}</span></div><div className="ats-big">{item.resume.final_score.toFixed(1)}<small>ATS SCORE</small></div></section><section className="metric-grid"><Metric label="Skill Match" value={item.resume.skill_score}/><Metric label="Semantic Match" value={item.resume.semantic_score}/><Metric label="Experience" value={item.resume.experience_score}/><Metric label="Education" value={item.resume.education_score}/><Metric label="Certification" value={item.resume.certification_score}/></section><section className="grid"><section className="panel"><h2>Candidate information</h2><Info label="Name" value={item.candidate_name||item.resume.name}/><Info label="Email" value={item.candidate_email||item.resume.email||'—'}/><Info label="Phone" value={item.resume.phone||'—'}/><Info label="Recommendation" value={item.resume.recommendation}/><h3 className="mt">Matched skills</h3>{(item.resume.parsed_data.matched_skills||[]).map((s:string)=><span className="chip good" key={s}>{s}</span>)}<h3 className="mt">Missing skills</h3>{(item.resume.parsed_data.missing_skills||[]).map((s:string)=><span className="chip missing" key={s}>{s}</span>)}</section><section className="panel"><h2>Recruiter decision</h2><p>AI analysis is automatic; the recruiter controls the final application status.</p><div className="status-actions">{['UNDER REVIEW','SHORTLISTED','INTERVIEW','REJECTED','HIRED'].map(s=><button className={item.status===s?'selected-status':''} key={s} onClick={()=>updateStatus(item.id,s)}>{s}</button>)}</div><h2 className="mt">AI suggestions shown to candidate</h2>{item.ai_suggestions.map((s,i)=><div className="suggestion" key={i}><Sparkles/><span>{s}</span></div>)}</section></section></>}
function Improvement({apps,onSelect}:{apps:AppItem[];onSelect:(a:AppItem)=>void}){return <section className="grid"><section className="panel"><h2>Resume improvement center</h2><p>AI suggestions are generated immediately after each application.</p>{apps.map(a=><div className="improve-card" key={a.id}><div><strong>{a.job.title}</strong><small>ATS {a.resume.final_score.toFixed(1)}%</small></div><button className="secondary" onClick={()=>onSelect(a)}>View suggestions</button></div>)}{!apps.length&&<Empty text="Apply for a job to receive personalized AI feedback."/>}</section><section className="panel"><h2>What the AI checks</h2>{['Required skills and missing skills','Resume-to-job semantic similarity','Relevant experience','Education alignment','Certifications','ATS-style overall match','Actionable resume improvement suggestions'].map(x=><div className="check-line" key={x}><CheckCircle2/>{x}</div>)}</section></section>}
function ApplicantTable({apps,onSelect,admin=false}:{apps:AppItem[];onSelect:(a:AppItem)=>void;admin?:boolean}){return <div className="table"><div className="tr th"><span>#</span><span>Candidate</span><span>Job</span><span>Skills</span><span>ATS</span><span>Status</span></div>{apps.map((a,i)=><button className="tr row-button" key={a.id} onClick={()=>onSelect(a)}><span>{i+1}</span><span><strong>{a.candidate_name||a.resume.name}</strong><small>{a.candidate_email||a.resume.email||a.resume.filename}</small></span><span>{a.job.title}</span><span>{a.resume.skill_score.toFixed(0)}%</span><span className="score">{a.resume.final_score.toFixed(1)}%</span><span><b className={`badge ${a.resume.recommendation.toLowerCase().replaceAll(' ','-')}`}>{admin?a.status:a.resume.recommendation}</b></span></button>)}{!apps.length&&<Empty text="No candidate applications yet."/>}</div>}
function Stats({stats}:{stats:any}){return <section className="stats big-stats"><Stat icon={<BriefcaseBusiness/>} value={stats.jobs||0} label="Jobs"/><Stat icon={<Users/>} value={stats.applications||0} label="Applications"/><Stat icon={<CheckCircle2/>} value={stats.shortlisted||0} label="Shortlisted"/><Stat icon={<Sparkles/>} value={stats.strong_matches||0} label="Strong AI matches"/><Stat icon={<Target/>} value={stats.average_score||0} label="Average ATS"/></section>}
function Reports({apps,stats}:{apps:AppItem[];stats:any}){const download=async()=>{const token=localStorage.getItem('resume_token');const r=await fetch(`${API}/admin/reports.csv`,{headers:{'X-User-Token':token||''}});const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='resume_screening_report.csv';a.click();URL.revokeObjectURL(url)};const dist=useMemo(()=>({strong:apps.filter(a=>a.resume.final_score>=85).length,short:apps.filter(a=>a.resume.final_score>=75&&a.resume.final_score<85).length,review:apps.filter(a=>a.resume.final_score>=60&&a.resume.final_score<75).length,low:apps.filter(a=>a.resume.final_score<60).length}),[apps]);return <><section className="stats big-stats"><Stat icon={<Target/>} value={stats.average_score||0} label="Average ATS"/><Stat icon={<Sparkles/>} value={dist.strong} label="Strong matches"/><Stat icon={<CheckCircle2/>} value={dist.short} label="Shortlist range"/><Stat icon={<Clock3/>} value={dist.review} label="Review"/></section><section className="grid"><section className="panel"><div className="section-head"><div><h2>Decision distribution</h2><p>Current AI ranking across applications.</p></div><button className="secondary" onClick={download}><Download/> CSV</button></div>{[['Strong Match',dist.strong],['Shortlist',dist.short],['Review',dist.review],['Low Match',dist.low]].map(([name,n]:any)=><div className="bar-row" key={name}><span>{name}</span><div><i style={{width:`${apps.length?(n/apps.length)*100:0}%`}}/></div><b>{n}</b></div>)}</section><section className="panel"><h2>Top candidates</h2>{[...apps].sort((a,b)=>b.resume.final_score-a.resume.final_score).slice(0,5).map(a=><button className="top-row" key={a.id}><span>{a.candidate_name}</span><b>{a.resume.final_score.toFixed(1)}%</b></button>)}</section></section></>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><span>{label}</span><strong>{value.toFixed(0)}%</strong><div><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="info"><span>{label}</span><strong>{value}</strong></div>}
function Stat({icon,value,label}:{icon:any;value:number|string;label:string}){return <div className="stat"><span className="stat-icon">{icon}</span><strong>{value}</strong><span>{label}</span></div>}
function Empty({text}:{text:string}){return <div className="empty"><AlertTriangleIcon/>{text}</div>}
function AlertTriangleIcon(){return <span className="empty-icon">△</span>}

createRoot(document.getElementById('root')!).render(<App/>);
